export const safelist = [
  'font-bold',
  'text-3xl',
  'md:text-4xl',
  'inline-block',
  'text-2xl',
  'md:text-3xl',
  'inline-block',
  'flex',
  'flex-col',
  'justify-center',
  'items-center',
  'items-start',
  'items-end',
  'gap-8',
  'md:(flex-row gap-16)',
  '[&>*]:(flex-grow basis-0)',
  'bg-gradient-to-tr',
  'from-green-500',
  'to-blue-500/75',
  'from-blue-500',
  'to-purple-500/75',
  'to-blue-700/75',
  'bg-gradient-to-br',
  'py-2',
  'my-4',
  'bg-clip-text',
  'text-transparent',
  'rounded-full',
  'px-4',
  'py-1',
  'border(solid 1)',
  'm-2',
  'shadow-lg',
  'text-white',
  'md:m-8',
  'text-center',
  'p-4',
  'm-4',
  'sm:(p-1 m-1)',
];
